### ISSUE TITLE
Searching is not working

### ISSUE THREAD

**Issue by eiffel-fl** [inspektor-gadget/website#61]
Hi!

I really like the new look and feel of the website.

Nonetheless, I am not sure to understand why you needed to modify `docs-fetcher.py`.
Moreover, I tried to search on the website and the search field display "Loading...":
![image](https://github.com/user-attachments/assets/6bfb6a2c-e3ca-4a64-9216-f23a7a4d3362)
I tried on both Firefox and Chromium and got the same result, is this expected because the site is in "preview mode"?

Best regards.

_Originally posted by @eiffel-fl in https://github.com/inspektor-gadget/website/pull/53#pullrequestreview-2212677211_

**Comment by andoriyaprashant** [comment]
Hello @eiffel-fl @mauriciovasquezbernal
I’d like to suggest enhancing our website's search feature by integrating Algolia, which would provide a more robust and efficient search experience. If this approach works for you, could you please assign me this issue

Thank you
